---
- hosts: all
  gather_facts: false
  become: yes
  vars:
      ansible_user: user
      ansible_password: password
      ansible_become_password: password


  tasks:
    - name: Update and install apache
      apt:
        name: apache2
        state: latest
        update_cache: true

    - name: Make directory
      file:
        path: /home/user/WebStorage
        state: directory
        mode: '0755'


    - name: Download website files
      git:
        repo: https://github.com/FrazerMichael/SDN-Lab2.git
        dest: /home/user/WebStorage
        clone: yes
        