---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Update and install apache
      apt:
        name: apache2
        state: latest
        update_cache: true

    - name: Make directory
      file:
        path: /home/user/WebStorage
        state: directory
        mode: '0755'

    - name: Download website files
      git:
        repo: https://github.com/FrazerMichael/SDN-Lab2.git
        dest: /home/user/WebStorage
        clone: yes

    - name: Move index file to /var/www/html
      copy:
        src: /home/user/WebStorage/index.html
        dest: /var/www/html
        remote_src: true

    - name: Restart and enable apache
      service:
        name: apache2
        state: restarted
        enabled: yes
      