---
- hosts: all
  gather_facts: true
  become: yes
  
  tasks:
    - name: Gather file
      command: cat error.log chdir=/var/log/apache2
      register: errorlog
    
    - name: Print log
      debug:
        msg: "{{errorlog.stdout}}"