---
- hosts: all
  gather_facts: true
  become: yes
  vars:
      ansible_user: user
      ansible_password: password
      ansible_become_password: password
      ansible_become: true
  
  tasks:
    - name: Gather file
      command: cat error.log chdir=/var/log/apache2
      register: errorlog
    
    - name: Print log
      debug:
        msg: "{{errorlog.stdout}}"