---
- hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Select user to see group membership
      command: groups "{{ user }}"
      register: groups
    
    - name: Print user's groups
      debug:
        msg: groups