---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: Add User
      user:
        name: "{{ username }}"
        password: "{{ password }}"
        groups: WebTeam, sudo
        append: yes
